//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_framework : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean Grip
        {
            get
            {
                return SteamVR_Actions.framework_Grip;
            }
        }
        
        public virtual SteamVR_Action_Single Squeeze
        {
            get
            {
                return SteamVR_Actions.framework_Squeeze;
            }
        }
        
        public virtual SteamVR_Action_Skeleton LeftHand
        {
            get
            {
                return SteamVR_Actions.framework_LeftHand;
            }
        }
        
        public virtual SteamVR_Action_Skeleton RightHand
        {
            get
            {
                return SteamVR_Actions.framework_RightHand;
            }
        }
        
        public virtual SteamVR_Action_Boolean TouchpadClick
        {
            get
            {
                return SteamVR_Actions.framework_TouchpadClick;
            }
        }
        
        public virtual SteamVR_Action_Boolean Trigger
        {
            get
            {
                return SteamVR_Actions.framework_Trigger;
            }
        }
        
        public virtual SteamVR_Action_Boolean Home
        {
            get
            {
                return SteamVR_Actions.framework_Home;
            }
        }
        
        public virtual SteamVR_Action_Boolean Menu
        {
            get
            {
                return SteamVR_Actions.framework_Menu;
            }
        }
        
        public virtual SteamVR_Action_Vector2 Touchpad
        {
            get
            {
                return SteamVR_Actions.framework_Touchpad;
            }
        }
        
        public virtual SteamVR_Action_Boolean Touch
        {
            get
            {
                return SteamVR_Actions.framework_Touch;
            }
        }
        
        public virtual SteamVR_Action_Pose Pose
        {
            get
            {
                return SteamVR_Actions.framework_Pose;
            }
        }
        
        public virtual SteamVR_Action_Vibration Haptic
        {
            get
            {
                return SteamVR_Actions.framework_Haptic;
            }
        }
    }
}
